import 'package:easy_localization/easy_localization.dart';

class ManagerStrings {
  static String get outboardingTitleOne => tr('outboardingTitleOne');
  static String get outboardingTitleTwo => tr('outboardingTitleTwo');
  static String get outboardingTitleThree => tr('outboardingTitleThree');
  static String get outboardingTitleFour => tr('outboardingTitleFour');
  static String get subtitle1 => tr('subtitle1');
  static String get start => tr('start');
  static String get naxt => tr('naxt');
  static String get skip => tr('skip');
  static String get welcome => tr('welcome');
  static String get new4shop => tr('new4shop');
  static String get signUp => tr('signUp');
  static String get signIn => tr('signIn');
  static String get visitor => tr('visitor');
  static String get login => tr('login');
  static String get email => tr('email');
  static String get password => tr('password');
  static String get rememberMe => tr('rememberMe');
  static String get forgetPassword => tr('forgetPassword');
  static String get haveAcoount => tr('haveAcoount');
  static String get or => tr('or');
  static String get username => tr('username');
  static String get numberCity => tr('numberCity');
  static String get confirmPassword => tr('confirmPassword');
  static String get alreadyhaveAcoount => tr('alreadyhaveAcoount');
  static String get notFoundRoute => tr('notFoundRoute');
  static String get mohammed => tr('mohammed');
  static String get home => tr('home');
  static String get search => tr('search');
  static String get bestProduct => tr('bestProduct');
  static String get showMore => tr('showMore');
  static String get features => tr('features');
  static String get discounted => tr('discounted');
  static String get emailRequired => tr('emailRequired');
  static String get passwordRequired => tr('passwordRequired');
  static String get loginSuccesfulleu => tr('loginSuccesfulleu');
  static String get productDetails => tr('productDetails');
  static String get details => tr('details');
  static String get reviews => tr('reviews');
  static String get more => tr('more');
  static String get addReview => tr('addReview');
  static String get notes => tr('notes');
  static String get writeHere => tr('writeHere');
  static String get price => tr('price');
}
